export const CHANGE_INPUT = 'CHANGE_INPUT';

export const CLICK_BUTTON = 'CLICK_BUTTON';

export const CLICK_BUTTON_EXIT = 'CLICK_BUTTON_EXIT';

// export const REQUEST_MANEA_ARTIST_PENDING = 'REQUEST_MANEA_ARTIST_PENDING';


// export const REQUEST_MANEA_ARTIST_SUCCESS = 'REQUEST_MANEA_ARTIST_SUCCESS';

// export const REQUEST_MANEA_ARTIST_FAILED = 'REQUEST_MANEA_ARTIST_FAILED';

export const REQUEST_ALL_MANELE_PENDING = 'REQUEST_ALL_MANELE_PENDING';
export const REQUEST_ALL_MANELE_SUCCESS = 'REQUEST_ALL_MANELE_SUCCESS';
export const REQUEST_ALL_MANELE_FAILED = 'REQUEST_ALL_MANELE_FAILED';

export const REQUEST_ALL_ARTISTS_PENDING = 'REQUEST_ALL_ARTISTS_PENDING';
export const REQUEST_ALL_ARTISTS_SUCCESS = 'REQUEST_ALL_ARTISTS_SUCCESS';
export const REQUEST_ALL_ARTISTS_FAILED = 'REQUEST_ALL_ARTISTS_FAILED';

export const REQUEST_ARTIST_PENDING = 'REQUEST_ARTIST_PENDING';
export const REQUEST_ARTIST_SUCCESS = 'REQUEST_ARTIST_SUCCESS';
export const REQUEST_ARTIST_FAILED = 'REQUEST_ARTIST_FAILED';

export const CLICK_ARTIST = 'CLICK_ARTIST';

export const MANEA_CHANGE = "MANEA_CHANGE";


export const REQUEST_MANEA_PENDING = 'REQUEST_MANEA_PENDING';
export const REQUEST_MANEA_SUCCESS = 'REQUEST_MANEA_SUCCESS';
export const REQUEST_MANEA_FAILED = 'REQUEST_MANEA_FAILED';

export const REQUEST_MANEA_BY_GEN_PENDING = 'REQUEST_MANEA_BY_GEN_PENDING';
export const REQUEST_MANEA_BY_GEN_SUCCESS = 'REQUEST_MANEA_BY_GEN_SUCCESS';
export const REQUEST_MANEA_BY_GEN_FAILED = 'REQUEST_MANEA_BY_GEN_FAILED';

export const CLICK_GENRE = 'CLICK_GENRE';

export const CHANGE_TITLE = 'CHANGE_TITLE';
export const CHANGE_GENRE = 'CHANGE_GENRE';
export const CHANGE_LINK = 'CHANGE_LINK';
export const CHANGE_ARTIST = 'CHANGE_ARTIST';


export const POST_MANEA_PENDING = 'POST_MANEA_PENDING';
export const POST_MANEA_SUCCESS = 'POST_MANEA_SUCCESS';
export const POST_MANEA_FAILED = 'POST_MANEA_FAILED';
