export const CHANGE_INPUT = 'CHANGE_INPUT';

export const CLICK_BUTTON = 'CLICK_BUTTON';

export const CLICK_BUTTON_EXIT = 'CLICK_BUTTON_EXIT';

export const REQUEST_MANEA_ARTIST_PENDING = 'REQUEST_MANEA_ARTIST_PENDING';


export const REQUEST_MANEA_ARTIST_SUCCESS = 'REQUEST_MANEA_ARTIST_SUCCESS';

export const REQUEST_MANEA_ARTIST_FAILED = 'REQUEST_MANEA_ARTIST_FAILED';
