export const CHANGE_INPUT = 'CHANGE_INPUT';

export const CLICK_BUTTON = 'CLICK_BUTTON';

export const CLICK_BUTTON_EXIT = 'CLICK_BUTTON_EXIT';

// export const REQUEST_MANEA_ARTIST_PENDING = 'REQUEST_MANEA_ARTIST_PENDING';


// export const REQUEST_MANEA_ARTIST_SUCCESS = 'REQUEST_MANEA_ARTIST_SUCCESS';

// export const REQUEST_MANEA_ARTIST_FAILED = 'REQUEST_MANEA_ARTIST_FAILED';

export const REQUEST_ALL_MANELE_PENDING = 'REQUEST_ALL_MANELE_PENDING';
export const REQUEST_ALL_MANELE_SUCCESS = 'REQUEST_ALL_MANELE_SUCCESS';
export const REQUEST_ALL_MANELE_FAILED = 'REQUEST_ALL_MANELE_FAILED';

export const REQUEST_ALL_ARTISTS_PENDING = 'REQUEST_ALL_ARTISTS_PENDING';
export const REQUEST_ALL_ARTISTS_SUCCESS = 'REQUEST_ALL_ARTISTS_SUCCESS';
export const REQUEST_ALL_ARTISTS_FAILED = 'REQUEST_ALL_ARTISTS_FAILED';

export const REQUEST_ARTIST_PENDING = 'REQUEST_ARTIST_PENDING';
export const REQUEST_ARTIST_SUCCESS = 'REQUEST_ARTIST_SUCCESS';
export const REQUEST_ARTIST_FAILED = 'REQUEST_ARTIST_FAILED';

export const CLICK_ARTIST = 'CLICK_ARTIST';

export const MANEA_CHANGE = "MANEA_CHANGE";